- name: Install, configure and deploy web page into nginx server
  hosts: all
  vars:
    greeting_msg: DevOps
    cm_tool: Ansible
    provisioner_tool: Docker
  tasks:
    - name: Install nginx web server in Ubuntu
      when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian" )
      apt: name=nginx state=latest update_cache=yes
      notify:
         - Restart the nginx web server

    - name: Install Extra Package for Enterprise Linux in CentOS 
      when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )
      yum: name=epel-release state=latest 
      notify:
         - Restart the nginx web server

    - name: Install nginx web server in CentOS 
      when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )
      yum: name=nginx state=latest 
      notify:
         - Restart the nginx web server

    - name: Create document root folder
      file: path=/var/html state=directory mode=0777

    - name: Configure nginx document root folder in Ubuntu
      when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian" )
      copy: src=default dest=/etc/nginx/sites-available/default
      notify:
         - Restart the nginx web server

    - name: Configure nginx document root folder in CentOS 
      when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )
      copy: src=default.conf dest=/etc/nginx/conf.d/default.conf
      notify:
         - Restart the nginx web server

    - name: Deploy customized web page
      template: src=index.html.j2 dest=/var/html/index.html

  handlers:
    - name: Restart the nginx web server
      shell: service nginx restart
